AccessKeyID="AKIA4GP5LTRFSUOEJ2NB"
SecretAccessKey="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"
MyRegion="ap-south-1"
MyBucket="maharajdev1"
MyVideoBucket="maharajvideos"
MyThumbnail="maharajthumbnail"
